apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::610054414151:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LGMN8Y5FZZUE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::610054414151:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T11:41:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1650"
  uid: 0dfbc428-d160-4532-9ab5-6f7b91862681
